DROP TABLE Location;
DROP TABLE ResourceTbl;
DROP TABLE EventPlanLine;
DROP TABLE EventPlan;
DROP TABLE Employee;
DROP TABLE EventRequest;
DROP TABLE Customer;
DROP TABLE Facility;

CREATE TABLE Employee
(EmpNo VARCHAR2(8) CONSTRAINT EmpNoNotNull NOT NULL,
     EmpName VARCHAR2(128) CONSTRAINT EmpNameNotNull NOT NULL,
     Department VARCHAR2(128) CONSTRAINT EmpDepartmentNotNull NOT NULL,
     Email VARCHAR2(128) CONSTRAINT EmpEmailNotNull NOT NULL,
     Phone VARCHAR2(32) CONSTRAINT EmpNotNull NOT NULL,
       CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EmpNo));

CREATE TABLE Customer 
(CustNo VARCHAR2(8) CONSTRAINT CustNoNotNull NOT NULL, 
     CustName VARCHAR2(30) CONSTRAINT CustNameNotNull NOT NULL, 
     Address VARCHAR2(50) CONSTRAINT AddressNotNull NOT NULL, 
     Internal CHAR(1) CONSTRAINT InternalNotNull NOT NULL, 
     Contact VARCHAR2(35) CONSTRAINT ContractNotNull NOT NULL, 
     Phone VARCHAR2(11) CONSTRAINT CPhoneNotNull NOT NULL, 
     City VARCHAR2(30) CONSTRAINT CityNotNull NOT NULL,
     State VARCHAR2(2) CONSTRAINT StateNotNull NOT NULL, 
     Zip VARCHAR2(10) CONSTRAINT zipNotNull NOT NULL,
       CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustNo) ) ;

CREATE TABLE Facility
(FacNo VARCHAR2(8) CONSTRAINT FacNoNotNull NOT NULL, 
     FacName VARCHAR2(30) CONSTRAINT FacNameNotNull NOT NULL,
       CONSTRAINT PK_FACILITY PRIMARY KEY (FacNo),
       CONSTRAINT Unique_FacName UNIQUE(FacName) );

CREATE TABLE EventRequest
(EventNo VARCHAR2(8) CONSTRAINT EREventNoNotNull NOT NULL,
     DateHeld DATE CONSTRAINT ERDateHeldNotNull NOT NULL,
     DateReq DATE CONSTRAINT ERDateRequestNotNull NOT NULL,
     CustNo VARCHAR2(8) CONSTRAINT ERCustNoNotNull NOT NULL,
     FacNo VARCHAR2(8) CONSTRAINT ERFacNoNotNull NOT NULL,
     DateAuth DATE,
     Status VARCHAR(32) CONSTRAINT ERStatus NOT NULL,
     EstCost NUMBER CONSTRAINT EREstCostNotNull NOT NULL,
     EstAudience NUMBER CONSTRAINT EREstAudienceNotNull NOT NULL,
     BudNo VARCHAR2(8),
       CONSTRAINT PK_EVENTREQUEST PRIMARY KEY (EventNo),
       CONSTRAINT FK_ERCUSTNO FOREIGN KEY (CustNo)
           REFERENCES Customer (CustNo),
       CONSTRAINT FK_ERFACNO FOREIGN KEY (FacNo)
           REFERENCES Facility (FacNo));

CREATE TABLE Location
(LocNo VARCHAR2(8) CONSTRAINT LocNoNotNull NOT NULL, 
     FacNo VARCHAR2(8) CONSTRAINT FacNoFKNotNull NOT NULL, 
     LocName VARCHAR2(30) CONSTRAINT LocNameNotNull NOT NULL,
       CONSTRAINT PK_LOCATION PRIMARY KEY (LocNo),
       CONSTRAINT FK_FACNO FOREIGN KEY (FacNo) 
           REFERENCES FACILITY (FacNo) );

CREATE TABLE ResourceTbl
(ResNo VARCHAR2(8) CONSTRAINT ResNoNotNull NOT NULL,
     ResName VARCHAR2(30) CONSTRAINT ResNameNotNull NOT NULL,
     Rate NUMBER CONSTRAINT RateNotNull NOT NULL,
       CONSTRAINT PK_ResourceTbl PRIMARY KEY (ResNo));

CREATE TABLE EventPlan
(PlanNo VARCHAR2(8) CONSTRAINT EPPlanNoNotNull NOT NULL,
     EventNo VARCHAR2(8) CONSTRAINT EPEventNoNotNull NOT NULL,
     WorkDate Date CONSTRAINT EPWorkDateNotNull NOT NULL,
     Notes VARCHAR(64),
     Activity VARCHAR(64) CONSTRAINT EPActivityNotNull NOT NULL,
     EmpNo VARCHAR2(8),
       CONSTRAINT PK_PlanNo PRIMARY KEY (PlanNo),
       CONSTRAINT FK_EventNo FOREIGN KEY (EventNo)
           REFERENCES EventRequest (EventNo),
       CONSTRAINT FK_EmpNo FOREIGN KEY (EmpNo)
           REFERENCES Employee (EmpNo));

CREATE TABLE EventPlanLine
(PlanNo VARCHAR2(8) CONSTRAINT EPLPlanNoNotNull NOT NULL,
     LineNo NUMBER CONSTRAINT LineNoNoNull NOT NULL,
     TimeStart DATE CONSTRAINT TimeStartNotNull NOT NULL,
     TimeEnd DATE CONSTRAINT TimeEndNotNull NOT NULL,
     NumberFld NUMBER CONSTRAINT NumberFldNotNull NOT NULL,
     LocNo VARCHAR2(8) CONSTRAINT EPLLocNoNotNull NOT NULL,
     ResNo VARCHAR2(8) CONSTRAINT EPLResNoNotNull NoT NULL,
       CONSTRAINT PK_EventPlanLine PRIMARY KEY (PlanNo, LineNo),
       CONSTRAINT FK_PlanNo FOREIGN KEY (PlanNo)
           REFERENCES EventPlan (PlanNo));

exit
